# Generated by Django 3.0.3 on 2020-02-23 11:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_code', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
